'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _d2I18n = require('@dhis2/d2-i18n');

var _d2I18n2 = _interopRequireDefault(_d2I18n);

var _translations = require('./ar/translations.json');

var _translations2 = _interopRequireDefault(_translations);

var _translations3 = require('./en/translations.json');

var _translations4 = _interopRequireDefault(_translations3);

var _translations5 = require('./nb/translations.json');

var _translations6 = _interopRequireDefault(_translations5);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by d2-i18n-generate.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var namespace = 'default';
_d2I18n2.default.addResources('ar', namespace, _translations2.default);
_d2I18n2.default.addResources('en', namespace, _translations4.default);
_d2I18n2.default.addResources('nb', namespace, _translations6.default);

exports.default = _d2I18n2.default;