'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _d2I18n = require('@dhis2/d2-i18n');

var _d2I18n2 = _interopRequireDefault(_d2I18n);

var _translations = require('./ar/translations.json');

var _translations2 = _interopRequireDefault(_translations);

var _translations3 = require('./cs/translations.json');

var _translations4 = _interopRequireDefault(_translations3);

var _translations5 = require('./en/translations.json');

var _translations6 = _interopRequireDefault(_translations5);

var _translations7 = require('./es/translations.json');

var _translations8 = _interopRequireDefault(_translations7);

var _translations9 = require('./fr/translations.json');

var _translations10 = _interopRequireDefault(_translations9);

var _translations11 = require('./nb/translations.json');

var _translations12 = _interopRequireDefault(_translations11);

var _translations13 = require('./pt/translations.json');

var _translations14 = _interopRequireDefault(_translations13);

var _translations15 = require('./zh/translations.json');

var _translations16 = _interopRequireDefault(_translations15);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var namespace = 'default'; //------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by d2-i18n-generate.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

_d2I18n2.default.addResources('ar', namespace, _translations2.default);
_d2I18n2.default.addResources('cs', namespace, _translations4.default);
_d2I18n2.default.addResources('en', namespace, _translations6.default);
_d2I18n2.default.addResources('es', namespace, _translations8.default);
_d2I18n2.default.addResources('fr', namespace, _translations10.default);
_d2I18n2.default.addResources('nb', namespace, _translations12.default);
_d2I18n2.default.addResources('pt', namespace, _translations14.default);
_d2I18n2.default.addResources('zh', namespace, _translations16.default);

exports.default = _d2I18n2.default;